function V = doppelpendel_rechte_seite(t,Y,g,l_1,l_2,m_1,m_2)
%DOPPELPENDEL_RECHTE_SEITE
%    V = DOPPELPENDEL_RECHTE_SEITE(T,Y,G,L_1,L_2,M_1,M_2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    02-Jun-2023 20:21:26

%Y(1): theta_2
%Y(2): Dtheta_2
%Y(3): theta_1
%Y(4): Dtheta_1
t2 = Y(1);
t3 = Y(2);
t4 = Y(3);
t5 = Y(4);
t6 = cos(t2);
t7 = cos(t4);
t8 = sin(t2);
t9 = sin(t4);
t10 = t3.^2;
t11 = t5.^2;
t12 = t6.^2;
t13 = t7.^2;
t14 = t7.^3;
t15 = t8.^2;
t16 = t9.^2;
t17 = t9.^3;
mt1 = [t3;-(g.*m_1.*t8.*t13+g.*m_2.*t8.*t13-g.*m_1.*t6.*t7.*t9-g.*m_2.*t6.*t7.*t9+l_1.*m_1.*t8.*t11.*t14-l_1.*m_1.*t6.*t11.*t17+l_1.*m_2.*t8.*t11.*t14-l_1.*m_2.*t6.*t11.*t17-l_1.*m_1.*t6.*t9.*t11.*t13+l_2.*m_2.*t6.*t8.*t10.*t13-l_1.*m_2.*t6.*t9.*t11.*t13-l_2.*m_2.*t7.*t9.*t10.*t12+l_1.*m_1.*t7.*t8.*t11.*t16-l_2.*m_2.*t6.*t8.*t10.*t16+l_1.*m_2.*t7.*t8.*t11.*t16+l_2.*m_2.*t7.*t9.*t10.*t15)./(l_2.*(m_1.*t12.*t13+m_1.*t12.*t16+m_1.*t13.*t15+m_2.*t12.*t16+m_2.*t13.*t15+m_1.*t15.*t16-m_2.*t6.*t7.*t8.*t9.*2.0));t5];
mt2 = [-(g.*m_1.*t9.*t12+g.*m_2.*t9.*t12+g.*m_1.*t9.*t15-g.*m_2.*t6.*t7.*t8-l_2.*m_2.*t7.*t8.^3.*t10+l_2.*m_2.*t6.^3.*t9.*t10-l_1.*m_2.*t6.*t8.*t11.*t13-l_2.*m_2.*t7.*t8.*t10.*t12+l_1.*m_2.*t7.*t9.*t11.*t12+l_1.*m_2.*t6.*t8.*t11.*t16+l_2.*m_2.*t6.*t9.*t10.*t15-l_1.*m_2.*t7.*t9.*t11.*t15)./(l_1.*m_1.*t12.*t13+l_1.*m_1.*t12.*t16+l_1.*m_1.*t13.*t15+l_1.*m_2.*t12.*t16+l_1.*m_2.*t13.*t15+l_1.*m_1.*t15.*t16-l_1.*m_2.*t6.*t7.*t8.*t9.*2.0)];
V = [mt1;mt2];
